server:
    port: 443
    ssl:
        key-alias: tomcat
        key-store: classpath:keystore.p12
        key-store-password: hta33550336
        key-store-type: PKCS12
        trust-store: classpath:truststore.p12
        trust-store-password: hta33550336
        trust-store-type: PKCS12
    address: www.smithsfallsnailsspa.com

spring:
    application:
        name: PMS
    datasource:
        url: jdbc:postgresql://160.191.50.248:5432/pms_db
        username: postgres
        password: 20226100
        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    time_zone: UTC+7
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: Asia/Ho_Chi_Minh
